import { StyleSheet } from 'react-native';
import { THEME } from '../../../theme';

export const styles = StyleSheet.create({
  loadingScreen: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: THEME.bgPrimary, gap: 12 },
  loadingText: { color: THEME.textMuted, fontSize: 14 },
  retryBtn: { marginTop: 8, backgroundColor: THEME.accent, paddingHorizontal: 24, paddingVertical: 10, borderRadius: 20 },
  retryBtnText: { color: '#fff', fontWeight: '700' },

  header: {
    paddingTop: 48,
    paddingBottom: 12,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: THEME.bgSecondary,
    borderBottomWidth: 1,
    borderBottomColor: THEME.border,
  },
  headerTitle: { flex: 1, fontSize: 18, fontWeight: '800', color: THEME.textPrimary },
  editIconBtn: { padding: 6 },
  editIconText: { fontSize: 20 },

  tabRow: {
    flexDirection: 'row',
    backgroundColor: THEME.bgSecondary,
    borderBottomWidth: 1,
    borderBottomColor: THEME.border,
  },
  tabBtn: { flex: 1, paddingVertical: 12, alignItems: 'center' },
  tabBtnActive: { borderBottomWidth: 2, borderBottomColor: THEME.accent },
  tabBtnText: { color: THEME.textMuted, fontWeight: '600', fontSize: 13 },
  tabBtnTextActive: { color: THEME.accent },

  bannerWrap: { width: '100%', height: 116, position: 'relative' },
  bannerImg: { width: '100%', height: 116 },
  bannerGradient: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.28)' },
  bannerEditHint: {
    position: 'absolute',
    bottom: 8,
    right: 12,
    backgroundColor: 'rgba(0,0,0,0.52)',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  bannerEditText: { color: '#fff', fontSize: 12, fontWeight: '600' },

  avatarSection: {
    paddingHorizontal: 16,
    paddingBottom: 16,
    backgroundColor: THEME.bgSecondary,
    marginBottom: 12,
  },
  avatarWrap: { marginTop: -44, marginBottom: 10, position: 'relative', alignSelf: 'flex-start' },
  avatarRing: {
    borderRadius: 48,
    borderWidth: 4,
    borderColor: THEME.statusOnline,
    backgroundColor: THEME.bgSecondary,
    padding: 2,
  },
  cameraIcon: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    backgroundColor: THEME.bgInput,
    borderRadius: 12,
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: THEME.bgSecondary,
  },

  nameBlock: { marginBottom: 8 },
  displayName: { fontSize: 22, fontWeight: '800', letterSpacing: 0.2 },
  handle: { fontSize: 13, color: THEME.textMuted, marginTop: 1 },
  statusTextLine: { fontSize: 12, color: THEME.textMuted, fontStyle: 'italic', marginTop: 3 },

  statusChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  statusDot: { width: 8, height: 8, borderRadius: 4 },
  statusChipText: { fontSize: 12, fontWeight: '700' },

  bioCard: {
    marginHorizontal: 12,
    marginBottom: 10,
    backgroundColor: THEME.bgSecondary,
    borderRadius: 12,
    padding: 14,
  },
  bioCardLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: THEME.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 6,
  },
  bioCardText: { color: THEME.textSecondary, fontSize: 14, lineHeight: 21 },

  bioEmptyCard: {
    marginHorizontal: 12,
    marginBottom: 10,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: THEME.border,
    borderStyle: 'dashed',
    padding: 14,
    alignItems: 'center',
  },
  bioEmptyText: { color: THEME.textMuted, fontSize: 14 },

  infoCard: {
    marginHorizontal: 12,
    marginBottom: 10,
    backgroundColor: THEME.bgSecondary,
    borderRadius: 12,
    padding: 14,
  },
  infoCardLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: THEME.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 12,
  },
  infoRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  infoSep: { height: 1, backgroundColor: THEME.border, marginVertical: 10 },
  infoRowIcon: { fontSize: 20, width: 28, textAlign: 'center' },
  infoRowLabel: { fontSize: 11, color: THEME.textMuted, marginBottom: 1 },
  infoRowValue: { fontSize: 14, color: THEME.textPrimary, fontWeight: '600' },
  verifiedRow: { gap: 6 },
  verifiedText: { color: THEME.textSecondary, fontSize: 12, fontWeight: '600' },

  settingsCard: {
    marginHorizontal: 12,
    marginBottom: 10,
    backgroundColor: THEME.bgSecondary,
    borderRadius: 12,
    overflow: 'hidden',
  },
  settingsCardLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: THEME.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 8,
  },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 13,
    gap: 12,
  },
  settingIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: THEME.bgInput,
    justifyContent: 'center',
    alignItems: 'center',
  },
  settingLabel: { fontSize: 15, color: THEME.textPrimary, fontWeight: '500' },
  settingSub: { fontSize: 12, color: THEME.textMuted, marginTop: 1 },
  settingArrow: { fontSize: 20, color: THEME.textMuted },
  sep: { height: 1, backgroundColor: THEME.border, marginLeft: 62 },

  logoutBtn: {
    marginHorizontal: 12,
    marginBottom: 8,
    backgroundColor: (THEME.danger || '#ed4245') + '18',
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: (THEME.danger || '#ed4245') + '44',
  },
  logoutBtnText: { color: THEME.danger || '#ed4245', fontWeight: '700', fontSize: 15 },

  qrScroll: { alignItems: 'center', paddingVertical: 24, paddingHorizontal: 16 },
  qrCard: {
    backgroundColor: THEME.bgSecondary,
    borderRadius: 20,
    width: '100%',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  qrBand: { height: 88, justifyContent: 'flex-end', alignItems: 'flex-start', paddingHorizontal: 20, paddingBottom: -32 },
  qrBody: { padding: 20, paddingTop: 28, alignItems: 'center' },
  qrName: { fontSize: 20, fontWeight: '800', marginBottom: 2 },
  qrHandle: { fontSize: 13, color: THEME.textMuted, marginBottom: 20 },
  qrCodeWrap: {
    backgroundColor: '#fff',
    padding: 14,
    borderRadius: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
  },
  qrCaption: { fontSize: 12, color: THEME.textMuted, textAlign: 'center', lineHeight: 18, marginBottom: 20 },
  copyLinkBtn: {
    backgroundColor: THEME.accent,
    borderRadius: 24,
    paddingHorizontal: 24,
    paddingVertical: 12,
    width: '100%',
    alignItems: 'center',
  },
  copyLinkText: { color: '#fff', fontWeight: '700', fontSize: 14 },

  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.72)', justifyContent: 'flex-end' },
  sheet: {
    backgroundColor: THEME.bgSecondary,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    padding: 20,
    paddingTop: 12,
    paddingBottom: 36,
  },
  sheetHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: THEME.textMuted + '66',
    alignSelf: 'center',
    marginBottom: 16,
  },
  sheetTitle: { fontSize: 18, fontWeight: '800', color: THEME.textPrimary, textAlign: 'center', marginBottom: 20 },
  fieldLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: THEME.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.7,
    marginBottom: 6,
  },
  fieldInput: {
    backgroundColor: THEME.bgInput,
    borderRadius: 10,
    padding: 13,
    color: THEME.textPrimary,
    fontSize: 15,
    marginBottom: 16,
    borderWidth: 1.5,
    borderColor: THEME.border,
  },
  sheetBtns: { flexDirection: 'row', gap: 12, marginTop: 4 },
  cancelBtn: {
    flex: 1,
    backgroundColor: THEME.bgInput,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  cancelBtnText: { color: THEME.textSecondary, fontWeight: '600', fontSize: 15 },
  saveBtn: {
    flex: 1,
    backgroundColor: THEME.accent,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  saveBtnText: { color: '#fff', fontWeight: '700', fontSize: 15 },

  statusOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 13,
    paddingHorizontal: 14,
    borderRadius: 10,
    marginBottom: 6,
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  statusOptionText: { fontSize: 15, color: THEME.textPrimary, fontWeight: '500' },

  colorGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
    justifyContent: 'center',
    marginBottom: 20,
  },
  colorSwatch: {
    width: 52,
    height: 52,
    borderRadius: 26,
    justifyContent: 'center',
    alignItems: 'center',
  },
  colorSwatchActive: { borderWidth: 3.5, borderColor: '#fff' },
});