export const SUPPORTED_LANGUAGES = [
  { code: 'English', name: 'Tiếng Anh' },
  { code: 'Vietnamese', name: 'Tiếng Việt' },
  { code: 'Chinese (Simplified)', name: 'Tiếng Trung (Giản thể)' },
  { code: 'Chinese (Traditional)', name: 'Tiếng Trung (Phồn thể)' },
  { code: 'Japanese', name: 'Tiếng Nhật' },
  { code: 'Korean', name: 'Tiếng Hàn' },
  { code: 'French', name: 'Tiếng Pháp' },
  { code: 'German', name: 'Tiếng Đức' },
  { code: 'Spanish', name: 'Tiếng Tây Ban Nha' },
  { code: 'Russian', name: 'Tiếng Nga' },
  { code: 'Portuguese', name: 'Tiếng Bồ Đào Nha' },
  { code: 'Italian', name: 'Tiếng Ý' },
  { code: 'Thai', name: 'Tiếng Thái' },
  { code: 'Indonesian', name: 'Tiếng Indonesia' },
  { code: 'Malay', name: 'Tiếng Mã Lai' },
  { code: 'Hindi', name: 'Tiếng Hindi' },
  { code: 'Arabic', name: 'Tiếng Ả Rập' },
  { code: 'Turkish', name: 'Tiếng Thổ Nhĩ Kỳ' },
  { code: 'Dutch', name: 'Tiếng Hà Lan' },
  { code: 'Polish', name: 'Tiếng Ba Lan' },
  { code: 'Swedish', name: 'Tiếng Thụy Điển' },
  { code: 'Danish', name: 'Tiếng Đan Mạch' },
  { code: 'Finnish', name: 'Tiếng Phần Lan' },
  { code: 'Norwegian', name: 'Tiếng Na Uy' },
  { code: 'Greek', name: 'Tiếng Hy Lạp' },
  { code: 'Hebrew', name: 'Tiếng Do Thái' },
  { code: 'Bengali', name: 'Tiếng Bengal' },
  { code: 'Panjabi', name: 'Tiếng Punjab' },
  { code: 'Javanese', name: 'Tiếng Java' },
  { code: 'Telugu', name: 'Tiếng Telugu' },
  { code: 'Marathi', name: 'Tiếng Marathi' },
  { code: 'Tamil', name: 'Tiếng Tamil' },
  { code: 'Urdu', name: 'Tiếng Urdu' },
  { code: 'Gujarati', name: 'Tiếng Gujarati' },
  { code: 'Kannada', name: 'Tiếng Kannada' },
  { code: 'Malayalam', name: 'Tiếng Malayalam' },
  { code: 'Sundanese', name: 'Tiếng Sunda' },
  { code: 'Hausa', name: 'Tiếng Hausa' },
  { code: 'Farsi', name: 'Tiếng Ba Tư' },
  { code: 'Burmese', name: 'Tiếng Miến Điện' },
  { code: 'Amharic', name: 'Tiếng Amharic' },
  { code: 'Oromo', name: 'Tiếng Oromo' },
  { code: 'Tagalog', name: 'Tiếng Tagalog' },
  { code: 'Yoruba', name: 'Tiếng Yoruba' },
  { code: 'Maithili', name: 'Tiếng Maithili' },
  { code: 'Uzbek', name: 'Tiếng Uzbek' },
  { code: 'Sindhi', name: 'Tiếng Sindhi' },
  { code: 'Amharic', name: 'Tiếng Amharic' },
  { code: 'Fula', name: 'Tiếng Fula' },
  { code: 'Pashto', name: 'Tiếng Pashto' },
  { code: 'Igbo', name: 'Tiếng Igbo' },
  { code: 'Hiligaynon', name: 'Tiếng Hiligaynon' },
  { code: 'Quechua', name: 'Tiếng Quechua' },
  { code: 'Chichewa', name: 'Tiếng Chichewa' },
  { code: 'Akan', name: 'Tiếng Akan' },
  { code: 'Zulu', name: 'Tiếng Zulu' },
  { code: 'Xhosa', name: 'Tiếng Xhosa' },
  { code: 'Kinyarwanda', name: 'Tiếng Kinyarwanda' },
  { code: 'Sesotho', name: 'Tiếng Sesotho' },
  { code: 'Tswana', name: 'Tiếng Tswana' },
  { code: 'Shona', name: 'Tiếng Shona' },
  { code: 'Tsonga', name: 'Tiếng Tsonga' },
  { code: 'Swati', name: 'Tiếng Swati' },
  { code: 'Venda', name: 'Tiếng Venda' },
  { code: 'Ndebele', name: 'Tiếng Ndebele' },
  { code: 'Afrikaans', name: 'Tiếng Afrikaans' },
  { code: 'Albanian', name: 'Tiếng Albania' },
  { code: 'Armenian', name: 'Tiếng Armenia' },
  { code: 'Azerbaijani', name: 'Tiếng Azerbaijan' },
  { code: 'Basque', name: 'Tiếng Basque' },
  { code: 'Belarusian', name: 'Tiếng Belarus' },
  { code: 'Bosnian', name: 'Tiếng Bosnia' },
  { code: 'Bulgarian', name: 'Tiếng Bulgaria' },
  { code: 'Catalan', name: 'Tiếng Catalan' },
  { code: 'Croatian', name: 'Tiếng Croatia' },
  { code: 'Czech', name: 'Tiếng Séc' },
  { code: 'Esperanto', name: 'Tiếng Esperanto' },
  { code: 'Estonian', name: 'Tiếng Estonia' },
  { code: 'Galician', name: 'Tiếng Galician' },
  { code: 'Georgian', name: 'Tiếng Gruzia' },
  { code: 'Gujarati', name: 'Tiếng Gujarati' },
  { code: 'Haitian Creole', name: 'Tiếng Haiti' },
  { code: 'Hungarian', name: 'Tiếng Hungary' },
  { code: 'Icelandic', name: 'Tiếng Iceland' },
  { code: 'Irish', name: 'Tiếng Ireland' },
  { code: 'Kazakh', name: 'Tiếng Kazakh' },
  { code: 'Khmer', name: 'Tiếng Khmer' },
  { code: 'Kyrgyz', name: 'Tiếng Kyrgyz' },
  { code: 'Lao', name: 'Tiếng Lào' },
  { code: 'Latvian', name: 'Tiếng Latvia' },
  { code: 'Lithuanian', name: 'Tiếng Lithuania' },
  { code: 'Macedonian', name: 'Tiếng Macedonia' },
  { code: 'Malagasy', name: 'Tiếng Malagasy' },
  { code: 'Maltese', name: 'Tiếng Malta' },
  { code: 'Maori', name: 'Tiếng Maori' },
  { code: 'Mongolian', name: 'Tiếng Mông Cổ' },
  { code: 'Nepali', name: 'Tiếng Nepal' },
  { code: 'Persian', name: 'Tiếng Ba Tư' },
  { code: 'Romanian', name: 'Tiếng Romania' },
  { code: 'Samoan', name: 'Tiếng Samoa' },
  { code: 'Serbian', name: 'Tiếng Serbia' },
  { code: 'Sinhala', name: 'Tiếng Sinhala' },
  { code: 'Slovak', name: 'Tiếng Slovak' },
  { code: 'Slovenian', name: 'Tiếng Slovenia' },
  { code: 'Somali', name: 'Tiếng Somali' },
  { code: 'Swahili', name: 'Tiếng Swahili' },
  { code: 'Tajik', name: 'Tiếng Tajik' },
  { code: 'Tatar', name: 'Tiếng Tatar' },
  { code: 'Tibetan', name: 'Tiếng Tây Tạng' },
  { code: 'Tigrinya', name: 'Tiếng Tigrinya' },
  { code: 'Tongan', name: 'Tiếng Tonga' },
  { code: 'Turkmen', name: 'Tiếng Turkmen' },
  { code: 'Ukrainian', name: 'Tiếng Ukraina' },
  { code: 'Uyghur', name: 'Tiếng Duy Ngô Nhĩ' },
  { code: 'Welsh', name: 'Tiếng Wales' },
  { code: 'Yiddish', name: 'Tiếng Yiddish' },
  // ... rút gọn còn các ngôn ngữ phổ biến nhất để demo, 
  // LLM thực tế có thể hiểu hàng nghìn ngôn ngữ qua text prompt
].sort((a, b) => a.name.localeCompare(b.name));
